name: SpikeHunter
n_gpu: 2
output: "test/predict_output.tsv"

data_loader:
  type: TsvDataLoader
  args:
    path_to_tsv: "/gpfs/gsfs12/users/yangy34/projects/SPICE/data_test/predict_a.tsv"
    batch_size: 50
    num_workers: 8
    shuffle: false
    prediction: true

arch:
  type: Baseline
  args:
    n_hidden: 568
    embedding_args:
      arch: roberta_large
      dropout: 0.0
      attention_dropout: 0.0
      activation_dropout: 0.0
      ffn_embed_dim: 5120
      layers: 33
      attention_heads: 20
      embed_dim: 1280
      learned_pos: true
      activation_fn: gelu
      use_bert_init: true
      normalize_before: true
      preact_normalize: true
      normalize_after: true
      token_dropout: true
      no_seed_provided: false
      pooler_activation_fn: 'tanh'
      pooler_dropout: 0.0
      checkpoint_transformer_block: false
      untie_weights_roberta: false
    embedding_pretrained: "/data/Irp-jiang/share/yyang/ESM/checkpoints/esm2_t33_650M_UR50D.pt"

transformer:
  type: ESM2Tokenize
  args: {}
